In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import LabelEncoder

# Load dataset
df = pd.read_csv('/content/Dataset  (1).csv')

# Display the first few rows
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [ ]:
# Check for missing values
print(df.isnull().sum())

# Fill or drop missing values based on your strategy
df.fillna('', inplace=True)

# View column names to decide which to use
print(df.columns)

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64
Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [ ]:
print(df.columns.tolist())

['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address', 'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two', 'Currency', 'Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu', 'Price range', 'Aggregate rating', 'Rating color', 'Rating text', 'Votes']

In [ ]:
print(df.columns.tolist())

['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address', 'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two', 'Currency', 'Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu', 'Price range', 'Aggregate rating', 'Rating color', 'Rating text', 'Votes']

In [ ]:
['Restaurant Name', 'Cuisines', 'Average Cost for two', 'City']

['Restaurant Name', 'Cuisines', 'Average Cost for two', 'City']

In [ ]:
df['combined_features'] = df['Cuisines'].astype(str) + ' ' + df['Average Cost for two'].astype(str) + ' ' + df['City'].astype(str)

In [ ]:
def recommend_restaurants(user_cuisine, user_price_range, user_location, top_n=5):
    user_input = user_cuisine + ' ' + user_price_range + ' ' + user_location
    user_vec = vectorizer.transform([user_input])

    sim_scores = cosine_similarity(user_vec, feature_matrix).flatten()
    top_indices = sim_scores.argsort()[-top_n:][::-1]

    return df.iloc[top_indices][['Restaurant Name', 'Cuisines', 'Average Cost for two', 'City']]

In [ ]:
vectorizer = TfidfVectorizer()
feature_matrix = vectorizer.fit_transform(df['combined_features'])

# Compute cosine similarity between restaurants
similarity = cosine_similarity(feature_matrix)

In [ ]:
def categorize_price(price):
    if price <= 300:
        return 'Low'
    elif price <= 600:
        return 'Medium'
    else:
        return 'High'

df['price_category'] = df['Average Cost for two'].apply(categorize_price)

In [ ]:
# Sample user preferences
user_cuisine = 'Italian'
user_price_range = 'Medium'
user_location = 'Downtown'

# Get recommendations
recommendations = recommend_restaurants(user_cuisine, user_price_range, user_location)
print("Top Recommended Restaurants:")
print(recommendations)

Top Recommended Restaurants:
     Restaurant Name Cuisines  Average Cost for two       City
3705       Sinyora's  Italian                   500  New Delhi
3603         Foodies  Italian                   300  New Delhi
3397   Da Pizza Farm  Italian                   400  New Delhi
7841       Pasta Hub  Italian                   200  New Delhi
1482  Chilli Indiana  Italian                   500    Gurgaon